name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: |
             docker build . --file Dockerfile --tag ghcr.io/vladvlasov256/twt2tgbot:latest
             docker push ghcr.io/vladvlasov256/twt2tgbot:latest
